"""
utils.py — Shared utilities for NMD ORF model v5: dataset, metrics, config loading.
"""

import json
import random
import re
from pathlib import Path

import h5py
import numpy as np
import torch
import os
import yaml
from sklearn.metrics import roc_auc_score, average_precision_score
from torch.utils.data import Dataset


# Config reading, path resolution and the selected-configuration tag all live in
# paths_config (no torch dependency); re-exported here so `from utils import load_config`
# keeps working for the scripts that already import utils for other reasons.
from paths_config import (PATH_ENV, load_config, resolve_path,  # noqa: E402,F401
                          selected_tag)


def set_seed(seed, deterministic=True):
    """Seed every RNG this pipeline draws from, and pin the nondeterministic GPU paths.

    WHY THIS IS MORE THAN THREE SEED CALLS (2026-07-27). This function used to set numpy,
    torch and cuda seeds only. That makes a run *reseeded*, not *reproducible*: cuDNN
    autotuning picks kernels by measured speed, and several backward kernels accumulate in
    nondeterministic order, so two runs with the same seed on the same machine can differ.
    The published AUC/AUPRC are headline numbers of §5 and are about to be regenerated by a
    retrain whose whole point is that a reader can rebuild them from the deposit. Numbers we
    cannot reproduce ourselves cannot be asked of anyone else.

    `deterministic=True` is the default deliberately. The escape hatch is an environment
    variable rather than a quiet argument default, so choosing speed over reproducibility is a
    visible act:

        NMD_ALLOW_NONDETERMINISM=1

    If an operation has no deterministic implementation, torch raises here rather than at the
    end of a long run -- and that is the intended behaviour. A `warn_only=True` would convert
    exactly the failure we want to see into a log line nobody reads, which is the
    always-succeeding fallback this project has already been caught by once.

    NOTE: determinism is per (hardware, library version). It makes OUR run repeatable and the
    numbers defensible; it does not promise bit-identical results on a reader's different GPU.
    Do not state more than that in REPRODUCTION.md.
    """
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

    if os.environ.get("NMD_ALLOW_NONDETERMINISM") == "1":
        print("  set_seed: NMD_ALLOW_NONDETERMINISM=1 -- determinism DISABLED by request. "
              "Results from this run are NOT reproducible and must not be published as canonical.")
        return

    if not deterministic:
        print("  set_seed: deterministic=False -- results from this run are not reproducible.")
        return

    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False        # autotuning picks kernels by timing: not stable
    # Required by cuBLAS for deterministic GEMMs on CUDA >= 10.2, and it must be set BEFORE the
    # first cuBLAS handle is created -- hence here, in the function every entry point calls first.
    os.environ.setdefault("CUBLAS_WORKSPACE_CONFIG", ":4096:8")
    torch.use_deterministic_algorithms(True)
    print(f"  set_seed: seed={seed}, deterministic algorithms ON "
          f"(cudnn.deterministic=True, benchmark=False)")




def member_tag(tag, seed=None):
    """Filename stem for ONE ensemble member. The single source of truth for member naming.

    WHY THIS EXISTS (2026-07-29). 03_train.py took its seed from `config` only -- there was no
    `--seed` -- and wrote `best_model_{tag}.pt`, a path with no seed slot. Five array tasks
    therefore `torch.save` to ONE filename, non-atomically: the five "members" of the ensemble
    are one checkpoint written five times, and the seed-variability table that is supposed to
    JUSTIFY the ensemble would read sd = 0. It would look like a stability result. It would be
    a filename collision.

    Seven call sites build that path (evaluate.py, deepshap.py, 11_kernel_shap_branches.py,
    05_interpret_structural.py, 05_export_sample_importance.py, run_infer_all.py,
    infer_uorf_attention.py). Encoding the rule here rather than repeating an f-string seven
    times is deliberate: a naming rule restated at seven call sites is a rule that will be
    seven different rules within a month.

    seed=None reproduces the legacy, pre-ensemble name, so artifacts already deposited under
    results_4ct/ and results_4ct_dn/ still resolve and nothing published is orphaned. Training
    never passes None -- 03_train.py resolves a concrete seed before it builds any path -- so
    no new seedless checkpoint can be written from here on.
    """
    return tag if seed is None else f"{tag}_seed{seed}"


def run_suffix(run_id=None):
    """Filename slot for ONE attribution replicate. The sibling of member_tag, and the same rule.

    WHY THIS EXISTS (2026-07-30). member_tag closed the MEMBER collision; the REPLICATE collision
    was left open one axis over. 11_kernel_shap_branches.py wrote
    `kernel_shap_branch_{member_tag(tag, member_seed)}{split}.tsv` and had no --run-id at all, so
    five background replicates on one member wrote one file, five times, non-atomically. The
    interpretation-variance component -- the whole reason replicates are run -- would have been
    measured over one surviving file, and it would have looked like a result.

    The two axes are NOT interchangeable and the spelling matters:

      member  (--member-seed)  which trained checkpoint  -> between-member / TRAINING variance
      run     (--run-id)       which background draw     -> within-member / INTERPRETATION variance

    Spelled `_run{N}` because deepshap.py already writes that and 06_export_deepshap_tsv.py
    already parses it back out (`f.stem.split("_run")[-1]`). A second spelling would be a second
    rule, and the consumer's glob would quietly stop matching -- which is how W52's mode suffix
    turned `if not run_files: return` into a silent skip of five claims.

    run_id=None reproduces the pre-replicate name byte for byte, so every deposited artifact still
    resolves and no existing consumer has to learn anything. Same contract as member_tag(tag, None).
    """
    return "" if run_id is None else f"_run{run_id}"


def members_in(paths):
    """The set of ensemble members a file list spans, read back out of the names member_tag wrote."""
    seeds = set()
    for p in paths:
        m = re.search(r"_seed(\d+)", Path(p).name)
        seeds.add(int(m.group(1)) if m else None)
    return seeds


def assert_one_member(paths, where):
    """Refuse a file set that spans more than one ensemble member. THE TRAP THIS EXISTS FOR:

    The producers learned about members (member_tag) and the consumers did not -- 06's
    `deepshap_summary_{tag}_{mode}_run*.tsv` does not match `{tag}_seed200_{mode}_run*.tsv`, so a
    member-tagged run makes the consumer fail LOUDLY, naming both paths. That is correct behaviour
    and nothing has been corrupted by it.

    The obvious repair is to loosen the glob to `{tag}*_{mode}_run*.tsv` so it "just finds the
    files". THAT IS THE DISASTER. It matches all five members, they get pooled into one mean, and
    the collapsed quantity is precisely the BETWEEN-MEMBER spread -- the training-variability
    estimate the whole two-variance design exists to produce. It would not error, would not warn,
    and would return a plausible number with the signal averaged out of it. Every other failure in
    this repo's history that cost a retraction had exactly that profile.

    So the repair is: give the consumer a --member-seed and build its path through member_tag,
    mirroring the producer. This guard sits at the glob site so that loosening it stops being a
    one-line edit that nobody reviews.
    """
    seeds = members_in(paths)
    if len(seeds) > 1:
        raise ValueError(
            f"{where}: matched files spanning {len(seeds)} ensemble members {sorted(seeds, key=str)}. "
            f"Pooling them would average away the between-member spread, which IS the training-"
            f"variability estimate. Pass --member-seed and match one member. Files: "
            f"{[Path(p).name for p in list(paths)[:4]]}")


def resolve_checkpoint(results_dir, tag, seed=None):
    """Locate ONE member's checkpoint, and refuse to guess which member.

    THE FAILURE THIS EXISTS TO PREVENT, which is nastier than the collision that motivated
    member_tag. Training now writes best_model_{tag}_seed{S}.pt. Consumers default to seed=None
    and therefore to the legacy best_model_{tag}.pt. So a reader who retrains and then evaluates
    with default flags would silently score the OLD, published checkpoint with the NEW run's
    label -- plausible numbers, exit 0, wrong model. That is precisely the shape of the
    2026-07-28 hybrid (deposit-native checkpoint scored over the published universe) and of C44
    (a finding reported off the wrong copy). Both were exit-0 and both were wrong.

    So: seed given -> that member must exist, or raise. seed omitted -> the legacy file is used
    ONLY if it exists; if it does not and seeded members do, raise and list them rather than
    picking one. Never silently fall back, in either direction.
    """
    results_dir = Path(results_dir)
    if seed is not None:
        path = results_dir / f"best_model_{member_tag(tag, seed)}.pt"
        if not path.exists():
            raise FileNotFoundError(
                f"No checkpoint for member seed={seed}: {path}. "
                f"Train it first, or pass a seed that exists.")
        return path

    legacy = results_dir / f"best_model_{tag}.pt"
    if legacy.exists():
        return legacy

    members = sorted(results_dir.glob(f"best_model_{tag}_seed*.pt"))
    if members:
        raise FileNotFoundError(
            f"{legacy} does not exist, but {len(members)} ensemble member(s) do:\n  "
            + "\n  ".join(p.name for p in members)
            + "\nPass --member-seed to name the member you mean. Refusing to guess: silently "
              "picking one would report a single member's number as the ensemble's.")
    raise FileNotFoundError(f"No checkpoint found: {legacy} (and no seeded members either).")


def _split_mask(splits, split):
    """THE ONE DEFINITION of what a split NAME selects, over a decoded `split` array.

    EXTRACTED 2026-07-30, same reasoning as evaluate.enforce_split_gate. It lived inside
    NMDDataset.__init__, so the only way to ask "which rows is split X?" was to construct the
    dataset -- which materialises that split's windows as float32, up to 28 GiB. A caller that
    only wants the row positions (to chunk them, or to label output rows) had the choice of
    paying that, or restating these seven branches. A restated copy is a second definition of
    what `test_clean` means, in a repo where D31 rests on `test` being touched once.
    """
    if split == "test_clean":
        return splits == "test"
    if split == "test_all":
        return (splits == "test") | (splits == "test_paralog")
    if split == "val_clean":
        # MIRRORS test_clean, AND REFUSES TO BE SILENTLY MEANINGLESS (2026-07-29).
        # data_prep only began screening VAL_CHRS for paralogs on 2026-07-29. On an
        # HDF5 built before that, `val` holds every chr2/chr4 transcript and NO
        # `val_paralog` label exists -- so `splits == "val"` would return the
        # UNSCREENED set while the name promised a screened one. Selecting a window
        # config on that set would reintroduce the leak the sweep exists to remove,
        # silently and at exit 0. An absent val_paralog label is therefore an error,
        # not an empty category: rebuild the HDF5.
        if not (splits == "val_paralog").any():
            raise ValueError(
                "split='val_clean' requested but this HDF5 contains no 'val_paralog' "
                "label, so `val` is UNSCREENED and val_clean would silently equal val. "
                "Rebuild the HDF5 with the current data_prep.py (which screens VAL_CHRS "
                "symmetrically with HOLDOUT_CHRS), or ask for split='val' explicitly if "
                "an unscreened validation set is genuinely what you want.")
        return splits == "val"
    if split == "val_all":
        return (splits == "val") | (splits == "val_paralog")
    if split == "all":
        return np.ones(len(splits), dtype=bool)   # every isoform (for full-cohort interpretation)
    return splits == split


def split_indices(h5_path, split):
    """Global row positions of a named split, WITHOUT materialising any window data.

    Reads only the `split` array -- 41,765 short strings -- so a caller can chunk a split, or
    name the isoforms it is about to explain, at negligible cost. Same names, same meanings and
    same val_clean guard as NMDDataset, because both go through _split_mask.
    """
    with h5py.File(Path(h5_path), "r") as f:
        splits = np.array([s.decode() if isinstance(s, bytes) else s for s in f["split"][:]])
    return np.where(_split_mask(splits, split))[0]


class NMDDataset(Dataset):
    """
    v5: PyTorch dataset — loads windows + minimal ORF features from HDF5.
    No tx_features (removed in v5).
    """

    def __init__(self, h5_path, window_size_atg, window_size_stop, split="train",
                 restrict_to=None):
        """restrict_to: positions WITHIN the split to keep, or None for all of it.

        WHY IT EXISTS (2026-07-30). This class materialises a split's window arrays as float32
        on construction. 11_kernel_shap_branches.py builds the whole `train` split -- 9.0 GB at
        atg1000_stop1000, 17.9 GB at atg2000_stop2000 -- in order to use 500 of its 26,711 rows
        as the SHAP reference set. Together with the explained cohort that is 46 GB for one run
        at the wider configuration, against a 32 GB SLURM request.

        Restricting here rather than reading the rows in the caller keeps normalization and the
        padded-ORF zeroing on ONE code path. A second reader would be a second place for the
        model contract to drift, and getting either wrong changes predictions silently.

        Default None reproduces the previous behaviour exactly, so evaluate.py, deepshap.py and
        ensemble_evaluate.py are unaffected.
        """
        self.h5_path = Path(h5_path)

        with h5py.File(self.h5_path, "r") as f:
            splits = np.array([s.decode() if isinstance(s, bytes) else s
                               for s in f["split"][:]])
            mask = _split_mask(splits, split)

            self.indices = np.where(mask)[0]
            if restrict_to is not None:
                sel = np.asarray(restrict_to, dtype=int)
                if sel.ndim != 1 or len(sel) == 0:
                    raise ValueError("restrict_to must be a non-empty 1-D array of positions")
                if len(np.unique(sel)) != len(sel):
                    raise ValueError(f"restrict_to has {len(sel) - len(np.unique(sel))} "
                                     f"duplicate position(s); a reference isoform would be "
                                     f"counted twice")
                if sel.min() < 0 or sel.max() >= len(self.indices):
                    raise ValueError(f"restrict_to holds positions outside split '{split}', "
                                     f"which has {len(self.indices):,} rows: min {sel.min()}, "
                                     f"max {sel.max()}")
                # Sorted for the HDF5 read below, which requires increasing indices. The rows
                # are used as an unordered reference set -- evaluate_coalition averages over
                # them -- so ordering carries no meaning to preserve.
                self.indices = self.indices[np.sort(sel)]
            n = len(self.indices)

            # Load window data into RAM
            self.atg_windows = f[f"w{window_size_atg}"]["atg_windows"][self.indices].astype(np.float32)
            self.stop_windows = f[f"w{window_size_stop}"]["stop_windows"][self.indices].astype(np.float32)

            self.orf_features = f["orf_features"][self.indices].astype(np.float32)
            self.orf_mask = f["orf_mask"][self.indices]
            self.labels = f["labels"][self.indices].astype(np.float32)

            # Load normalization stats
            self.orf_feat_mean = f["normalization/orf_feat_mean"][:].astype(np.float32)
            self.orf_feat_std = f["normalization/orf_feat_std"][:].astype(np.float32)

        # Apply normalization to ORF features
        self.orf_features = (self.orf_features - self.orf_feat_mean) / self.orf_feat_std

        # Zero out normalized features for padded ORFs
        self.orf_features[~self.orf_mask] = 0.0

        scope = split if restrict_to is None else f"{split}[{n:,} of {int(mask.sum()):,}]"
        print(f"  {scope}: {n:,} samples, {self.labels.sum():.0f} NMD+ "
              f"({self.labels.mean()*100:.1f}%)")

    def __len__(self):
        return len(self.indices)

    def __getitem__(self, idx):
        return {
            "atg_windows": torch.from_numpy(self.atg_windows[idx]),
            "stop_windows": torch.from_numpy(self.stop_windows[idx]),
            "orf_features": torch.from_numpy(self.orf_features[idx]),
            "orf_mask": torch.from_numpy(self.orf_mask[idx]),
            "label": torch.tensor(self.labels[idx], dtype=torch.float32),
        }


def compute_pos_weight(dataset):
    """Compute pos_weight for BCEWithLogitsLoss from label distribution."""
    n_pos = dataset.labels.sum()
    n_neg = len(dataset.labels) - n_pos
    return torch.tensor(n_neg / max(n_pos, 1), dtype=torch.float32)


def compute_metrics(labels, logits):
    """Compute AUC and AUPRC from labels and raw logits."""
    probs = torch.sigmoid(torch.tensor(logits)).numpy()
    labels = np.array(labels)
    auc = roc_auc_score(labels, probs)
    auprc = average_precision_score(labels, probs)
    return {"auc": auc, "auprc": auprc}
