"""
utils.py — Shared utilities for NMD ORF model v5: dataset, metrics, config loading.
"""

import json
import random
from pathlib import Path

import h5py
import numpy as np
import torch
import os
import yaml
from sklearn.metrics import roc_auc_score, average_precision_score
from torch.utils.data import Dataset


def load_config(config_path="config.yaml"):
    with open(config_path) as f:
        return yaml.safe_load(f)


# Path resolution lives in paths_config (no torch dependency); re-exported
# here so `from utils import resolve_path` keeps working.
from paths_config import PATH_ENV, resolve_path  # noqa: E402,F401


def set_seed(seed, deterministic=True):
    """Seed every RNG this pipeline draws from, and pin the nondeterministic GPU paths.

    WHY THIS IS MORE THAN THREE SEED CALLS (2026-07-27). This function used to set numpy,
    torch and cuda seeds only. That makes a run *reseeded*, not *reproducible*: cuDNN
    autotuning picks kernels by measured speed, and several backward kernels accumulate in
    nondeterministic order, so two runs with the same seed on the same machine can differ.
    The published AUC/AUPRC are headline numbers of §5 and are about to be regenerated by a
    retrain whose whole point is that a reader can rebuild them from the deposit. Numbers we
    cannot reproduce ourselves cannot be asked of anyone else.

    `deterministic=True` is the default deliberately. The escape hatch is an environment
    variable rather than a quiet argument default, so choosing speed over reproducibility is a
    visible act:

        NMD_ALLOW_NONDETERMINISM=1

    If an operation has no deterministic implementation, torch raises here rather than at the
    end of a long run -- and that is the intended behaviour. A `warn_only=True` would convert
    exactly the failure we want to see into a log line nobody reads, which is the
    always-succeeding fallback this project has already been caught by once.

    NOTE: determinism is per (hardware, library version). It makes OUR run repeatable and the
    numbers defensible; it does not promise bit-identical results on a reader's different GPU.
    Do not state more than that in REPRODUCTION.md.
    """
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

    if os.environ.get("NMD_ALLOW_NONDETERMINISM") == "1":
        print("  set_seed: NMD_ALLOW_NONDETERMINISM=1 -- determinism DISABLED by request. "
              "Results from this run are NOT reproducible and must not be published as canonical.")
        return

    if not deterministic:
        print("  set_seed: deterministic=False -- results from this run are not reproducible.")
        return

    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False        # autotuning picks kernels by timing: not stable
    # Required by cuBLAS for deterministic GEMMs on CUDA >= 10.2, and it must be set BEFORE the
    # first cuBLAS handle is created -- hence here, in the function every entry point calls first.
    os.environ.setdefault("CUBLAS_WORKSPACE_CONFIG", ":4096:8")
    torch.use_deterministic_algorithms(True)
    print(f"  set_seed: seed={seed}, deterministic algorithms ON "
          f"(cudnn.deterministic=True, benchmark=False)")


def member_tag(tag, seed=None):
    """Filename stem for ONE ensemble member. The single source of truth for member naming.

    WHY THIS EXISTS (2026-07-29). 03_train.py took its seed from `config` only -- there was no
    `--seed` -- and wrote `best_model_{tag}.pt`, a path with no seed slot. Five array tasks
    therefore `torch.save` to ONE filename, non-atomically: the five "members" of the ensemble
    are one checkpoint written five times, and the seed-variability table that is supposed to
    JUSTIFY the ensemble would read sd = 0. It would look like a stability result. It would be
    a filename collision.

    Seven call sites build that path (evaluate.py, deepshap.py, 11_kernel_shap_branches.py,
    05_interpret_structural.py, 05_export_sample_importance.py, run_infer_all.py,
    infer_uorf_attention.py). Encoding the rule here rather than repeating an f-string seven
    times is deliberate: a naming rule restated at seven call sites is a rule that will be
    seven different rules within a month.

    seed=None reproduces the legacy, pre-ensemble name, so artifacts already deposited under
    results_4ct/ and results_4ct_dn/ still resolve and nothing published is orphaned. Training
    never passes None -- 03_train.py resolves a concrete seed before it builds any path -- so
    no new seedless checkpoint can be written from here on.
    """
    return tag if seed is None else f"{tag}_seed{seed}"


def resolve_checkpoint(results_dir, tag, seed=None):
    """Locate ONE member's checkpoint, and refuse to guess which member.

    THE FAILURE THIS EXISTS TO PREVENT, which is nastier than the collision that motivated
    member_tag. Training now writes best_model_{tag}_seed{S}.pt. Consumers default to seed=None
    and therefore to the legacy best_model_{tag}.pt. So a reader who retrains and then evaluates
    with default flags would silently score the OLD, published checkpoint with the NEW run's
    label -- plausible numbers, exit 0, wrong model. That is precisely the shape of the
    2026-07-28 hybrid (deposit-native checkpoint scored over the published universe) and of C44
    (a finding reported off the wrong copy). Both were exit-0 and both were wrong.

    So: seed given -> that member must exist, or raise. seed omitted -> the legacy file is used
    ONLY if it exists; if it does not and seeded members do, raise and list them rather than
    picking one. Never silently fall back, in either direction.
    """
    results_dir = Path(results_dir)
    if seed is not None:
        path = results_dir / f"best_model_{member_tag(tag, seed)}.pt"
        if not path.exists():
            raise FileNotFoundError(
                f"No checkpoint for member seed={seed}: {path}. "
                f"Train it first, or pass a seed that exists.")
        return path

    legacy = results_dir / f"best_model_{tag}.pt"
    if legacy.exists():
        return legacy

    members = sorted(results_dir.glob(f"best_model_{tag}_seed*.pt"))
    if members:
        raise FileNotFoundError(
            f"{legacy} does not exist, but {len(members)} ensemble member(s) do:\n  "
            + "\n  ".join(p.name for p in members)
            + "\nPass --seed to name the member you mean. Refusing to guess: silently "
              "picking one would report a single member's number as the ensemble's.")
    raise FileNotFoundError(f"No checkpoint found: {legacy} (and no seeded members either).")


class NMDDataset(Dataset):
    """
    v5: PyTorch dataset — loads windows + minimal ORF features from HDF5.
    No tx_features (removed in v5).
    """

    def __init__(self, h5_path, window_size_atg, window_size_stop, split="train"):
        self.h5_path = Path(h5_path)

        with h5py.File(self.h5_path, "r") as f:
            splits = np.array([s.decode() if isinstance(s, bytes) else s
                               for s in f["split"][:]])
            if split == "test_clean":
                mask = splits == "test"
            elif split == "test_all":
                mask = (splits == "test") | (splits == "test_paralog")
            elif split == "all":
                mask = np.ones(len(splits), dtype=bool)   # every isoform (for full-cohort interpretation)
            else:
                mask = splits == split

            self.indices = np.where(mask)[0]
            n = len(self.indices)

            # Load window data into RAM
            self.atg_windows = f[f"w{window_size_atg}"]["atg_windows"][self.indices].astype(np.float32)
            self.stop_windows = f[f"w{window_size_stop}"]["stop_windows"][self.indices].astype(np.float32)

            self.orf_features = f["orf_features"][self.indices].astype(np.float32)
            self.orf_mask = f["orf_mask"][self.indices]
            self.labels = f["labels"][self.indices].astype(np.float32)

            # Load normalization stats
            self.orf_feat_mean = f["normalization/orf_feat_mean"][:].astype(np.float32)
            self.orf_feat_std = f["normalization/orf_feat_std"][:].astype(np.float32)

        # Apply normalization to ORF features
        self.orf_features = (self.orf_features - self.orf_feat_mean) / self.orf_feat_std

        # Zero out normalized features for padded ORFs
        self.orf_features[~self.orf_mask] = 0.0

        print(f"  {split}: {n:,} samples, {self.labels.sum():.0f} NMD+ "
              f"({self.labels.mean()*100:.1f}%)")

    def __len__(self):
        return len(self.indices)

    def __getitem__(self, idx):
        return {
            "atg_windows": torch.from_numpy(self.atg_windows[idx]),
            "stop_windows": torch.from_numpy(self.stop_windows[idx]),
            "orf_features": torch.from_numpy(self.orf_features[idx]),
            "orf_mask": torch.from_numpy(self.orf_mask[idx]),
            "label": torch.tensor(self.labels[idx], dtype=torch.float32),
        }


def compute_pos_weight(dataset):
    """Compute pos_weight for BCEWithLogitsLoss from label distribution."""
    n_pos = dataset.labels.sum()
    n_neg = len(dataset.labels) - n_pos
    return torch.tensor(n_neg / max(n_pos, 1), dtype=torch.float32)


def compute_metrics(labels, logits):
    """Compute AUC and AUPRC from labels and raw logits."""
    probs = torch.sigmoid(torch.tensor(logits)).numpy()
    labels = np.array(labels)
    auc = roc_auc_score(labels, probs)
    auprc = average_precision_score(labels, probs)
    return {"auc": auc, "auprc": auprc}
